### ISSUE TITLE
Rework placement of homepage and project widgets

### ISSUE THREAD

**Issue by jmullins63** [MullinsLab/viroverse#51]
please let me know if you need more info on this

**Comment by silby** [comment]
My concept for this:

- Move project status panels ("All Active Projects") to projects index, in lieu of the simple tabular list of active projects. (Check in with bench scientists on this.)
- Duplicate list of cohorts from cohort index (not patient groups) onto homepage below "My assigned samples"
    - Subset further to a selection of "interesting"/"active" cohorts? (F/U with Jim et al on this.) Would require a config item or a flag on cohort table. 
- Hide Assigned Samples section of homepage entirely when user has no assignments.
