### ISSUE TITLE
Facet primers by regions the targeted position is in rather than exact position

### ISSUE THREAD

**Issue by fluffy-critter** [MullinsLab/viroverse#69]
When searching for a primer we only really care about its position being in the neighborhood of where we want it rather than the exact position. So for example, if we have primers that live at positions 50, 55, 65, 1200, 1240, and 2345, we'd want to split them up into buckets like 50-65, 1200-1240, and 2345, and make those the facets that get searched on.

Modeling this in the data is straightforward but actually building the materialized view this way is tricky and will probably require a two-pass operation at the very least.

One possibility is to create a PrimerPositionBucket type which Primer has a `has_many` relationship with; if we do this we might not even need the materialized view at all anymore.

**Comment by silby** [comment]
A simpler approach would just involve translating the snippet `WHERE abs(hxb2_start - query) < 5)` into the array context, which might be doable with `ANY`; the `search_array_overlaps` helper method probably doesn't apply here

**Comment by fluffy-critter** [comment]
If we're going to filter primers based on position wouldn't it make sense to limit the number of positions that could be filtered on though?

**Comment by silby** [comment]
I'm thinking in terms of including positions in the freeform search. If I type `5941` in the search box, with a target position I want in mind, I might expect (harder) the nearest primers or (easier) all primers within ∆ base pairs for some well-chosen ∆.

**Comment by silby** [comment]
Retitled this to make it about faceting on region, a modification to the freeform search as I described likely wouldn't have nearly as much demand or usability
