### ISSUE TITLE
Rework global navigation

### ISSUE THREAD

**Issue by silby** [MullinsLab/viroverse#82]
With some recent changes and additions, the global navigation structure (top nav and the contents of the "starter" pages you can reach by clicking on it) feels out of date, and a couple things are now accessible only from the footer nav.

Things may need to be reworked, with guidance from both data-entry-focused and data-retrieval-focused users. If people are happy as-is, not necessarily any need to change anything.

Thoughts I've had about what could be better:

* New shared design for "start pages" for related tasks, with friendly chunky links and possibly even attractive icons to go with the chunky links
* Separate freezer management from the "Admin" container and give it its own start page
* New "Enter data" start page, with the "import" regrouped there as a part of data entry
* New "Browse" start page linking into cohort browsing and the various global searches
* New "Admin" start page to only contain the things actually restricted to admins (adding new controlled vocabulary items and user management). (the "Admin" button in the top nav would then only need to be visible to users with the `supervisor` or `admin` role)

**Comment by fluffy-critter** [comment]
Issue broken out into subtasks, project started to track them as a unit.
